# Generated by Django 5.0.7 on 2024-07-19 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('O_id', models.IntegerField()),
                ('OrderDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_id', models.IntegerField()),
                ('P_name', models.CharField(max_length=20)),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('U_id', models.IntegerField()),
                ('U_name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pay_id', models.IntegerField()),
                ('Pay_status', models.CharField(max_length=20)),
                ('O_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='allRelations.orders')),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='P_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allRelations.product'),
        ),
        migrations.AddField(
            model_name='orders',
            name='U_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allRelations.users'),
        ),
    ]
